import React, { Component } from "react";
import rendering from './rendering.jpg';
 
class Home extends Component {
  render() {
    return (
      <div>
        <h2>Works</h2>

<p>Center for Advanced Visual Studies Special Collection
Works, People, About, Search
Welcome to the online repository of MIT's Center for Advanced Visual Studies (CAVS) Special Collection, part of the Program in Art, Culture and Technology (ACT) Archives and Special Collections. This site presents experimental ways in which to explore collection materials.
The CAVS Special Collection documents a nearly 45 year history of collaborative and time-based productions generated by over 200 internationally recognized artist-fellows. This digitized, virtual museum includes images, publications, posters, documents, portfolios, videos and other materials of historic importance documenting the process of creating art-science-technology projects at CAVS.
</p>
                
                

      </div>
    );
  }
}
 
export default Home;